### PR TITLE
Read from tarball

### PR DESCRIPTION
**Pull request by bestouff**
Should cover all basic cases.

### CODE REVIEW

**Comment by bestouff** [comment]
@josch care to give it a look before I merge ?

**Comment by josch** [comment]
`res = (res << 8) + field[i];` in line 2183 left-shifts a negative number which is undefined behaviour.

Your header check in line 2238 matches none of my tarballs. The magic value my tarballs have there is `75 7374 6172 2020 0000`.

**Comment by bestouff** [comment]
> res = (res << 8) + field[i]; in line 2183 left-shifts a negative number which is undefined behaviour.

Good catch. I do too much Rust nowadays, I'm not used to silent UB anymore :/

> Your header check in line 2238 matches none of my tarballs. The magic value my tarballs have there is 75 7374 6172 2020 0000.

Yes, I wrongly removed the check in 7cc168217c7df39862d010f3f95fe1c8673c7432 after reading the wiki page; I'll reintroduce it.

**Comment by josch** [comment]
Maybe add a section explaining the limitations of your parser. For example v7 and pax are not supported. Also, your implementation requires that the directories come in the tarball *before* the files contained in them -- you can fix this by always creating the full path of a file before extracting it (this becomes a bit complex when symlinks are involved). Also for hardlinks you require that the destination comes before the link to it in the tarball.

Also, did you test tarballs containing directories as input? The dirname/basename split is even done on type '5' entries, so that the directories will not be created with the full path. Since directories don't get created correctly, later files cannot get extracted properly.

I think useful test cases for you while developing on this are tarballs of popular distributions like:

 - fedora: https://dl.fedoraproject.org/pub/fedora/linux/releases/30/Container/x86_64/images/
 - ubuntu: https://cloud-images.ubuntu.com/xenial/current/
 - debian: https://cloud.debian.org/images/cloud/sid/daily/20200514-263/

because an important use-case for creating an ext2 image from a tarball is for creating a system image with the correct permission and ownership information.

**Pull request merged**
